// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511200950_Migration6")]
    partial class Migration6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Web.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SalesGroupID")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TwoFAType")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UsernameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Web.Data.Models.BlankCategory", b =>
                {
                    b.Property<int>("categoryID")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryID");

                    b.ToTable("BlankCategories");
                });

            modelBuilder.Entity("Web.Data.Models.BlankProduct", b =>
                {
                    b.Property<int>("skuID_Master")
                        .HasColumnType("int");

                    b.Property<string>("brandName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("caseHeight")
                        .HasColumnType("float");

                    b.Property<double>("caseLength")
                        .HasColumnType("float");

                    b.Property<double>("casePrice")
                        .HasColumnType("float");

                    b.Property<int>("caseQty")
                        .HasColumnType("int");

                    b.Property<double>("caseWeight")
                        .HasColumnType("float");

                    b.Property<double>("caseWidth")
                        .HasColumnType("float");

                    b.Property<string>("color1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorBackImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorDirectSideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("colorFamilyID")
                        .HasColumnType("int");

                    b.Property<string>("colorFrontImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("colorOnModelBackImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorOnModelFrontImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorOnModelSideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorPriceCodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorSideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorSwatchImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorSwatchTextColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("customerPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("dateLastChanged")
                        .HasColumnType("datetime2");

                    b.Property<double>("dozenPrice")
                        .HasColumnType("float");

                    b.Property<string>("gtin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("mapPrice")
                        .HasColumnType("float");

                    b.Property<bool>("noeRetailing")
                        .HasColumnType("bit");

                    b.Property<double>("piecePrice")
                        .HasColumnType("float");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("saleExpiration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salePrice")
                        .HasColumnType("float");

                    b.Property<string>("sizeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("sizeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sizeOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sizePriceCodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("styleID")
                        .HasColumnType("int");

                    b.Property<string>("styleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("unitWeight")
                        .HasColumnType("float");

                    b.Property<string>("yourSku")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("skuID_Master");

                    b.ToTable("BlankProducts");
                });

            modelBuilder.Entity("Web.Data.Models.BlankSanMar", b =>
                {
                    b.Property<int>("UNIQUE_KEY")
                        .HasColumnType("int");

                    b.Property<string>("AVAILABLE_SIZES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BACK_FLAT_IMAGE_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BACK_MODEL_IMAGE_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRAND_LOGO_IMAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CASE_PRICE")
                        .HasColumnType("float");

                    b.Property<int>("CASE_SIZE")
                        .HasColumnType("int");

                    b.Property<string>("CATEGORY_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOR_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOR_PRODUCT_IMAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOR_PRODUCT_IMAGE_THUMBNAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOR_SQUARE_IMAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOR_SWATCH_IMAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPANION_STYLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DECORATION_SPEC_SHEET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DOZENS_PRICE")
                        .HasColumnType("float");

                    b.Property<string>("FRONT_FLAT_IMAGE_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_MODEL_IMAGE_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GTIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INVENTORY_KEY")
                        .HasColumnType("int");

                    b.Property<string>("MAP_PRICING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MILL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MSRP")
                        .HasColumnType("float");

                    b.Property<double>("PIECE_PRICE")
                        .HasColumnType("float");

                    b.Property<double>("PIECE_WEIGHT")
                        .HasColumnType("float");

                    b.Property<string>("PMS_COLOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRICE_GROUP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRICE_TEXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCT_DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCT_IMAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCT_MEASUREMENTS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCT_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCT_TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SANMAR_MAINFRAME_COLOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SIZE_INDEX")
                        .HasColumnType("int");

                    b.Property<int>("SIZE_SORT")
                        .HasColumnType("int");

                    b.Property<string>("SPEC_SHEET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STYLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBCATEGORY_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SUGGESTED_PRICE")
                        .HasColumnType("float");

                    b.Property<string>("THUMBNAIL_IMAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateLastChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("UNIQUE_KEY");

                    b.ToTable("BlankSanMar");
                });

            modelBuilder.Entity("Web.Data.Models.BlankStyle", b =>
                {
                    b.Property<int>("styleID")
                        .HasColumnType("int");

                    b.Property<string>("baseCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("boxRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brandImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catalogPageNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companionGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comparableGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateLastChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("newStyle")
                        .HasColumnType("bit");

                    b.Property<string>("noeRetailing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("styleImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("styleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uniqueStyleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("styleID");

                    b.ToTable("BlankStyles");
                });

            modelBuilder.Entity("Web.Data.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fkCompany");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Privledged")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Web.Data.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Privledged")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesGroupID")
                        .HasColumnType("int")
                        .HasColumnName("fkSalesGroup");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Web.Data.Models.PriceMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<decimal>("Markup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MatrixName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxColors")
                        .HasColumnType("int");

                    b.Property<int>("MinUnits")
                        .HasColumnType("int");

                    b.Property<int>("SalesGroupID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesGroupID");

                    b.ToTable("PriceMatrices");
                });

            modelBuilder.Entity("Web.Data.Models.PriceMatrixPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("LevelMaxCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OtherPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId");

                    b.ToTable("PriceMatrixPrices");
                });

            modelBuilder.Entity("Web.Data.Models.PriceMatrixProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LowerThreshold")
                        .HasColumnType("int");

                    b.Property<decimal>("PropertyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("SalesGroupID")
                        .HasColumnType("int");

                    b.Property<int?>("UpperThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PriceMatrixProperties");
                });

            modelBuilder.Entity("Web.Data.Models.SalesGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyingUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSubscribed")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesGroupEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandSAPIKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandSAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalesGroups");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Web.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Web.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Web.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web.Data.Models.Client", b =>
                {
                    b.HasOne("Web.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Web.Data.Models.PriceMatrix", b =>
                {
                    b.HasOne("Web.Data.Models.SalesGroup", "SalesGroup")
                        .WithMany()
                        .HasForeignKey("SalesGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesGroup");
                });

            modelBuilder.Entity("Web.Data.Models.PriceMatrixPrice", b =>
                {
                    b.HasOne("Web.Data.Models.PriceMatrix", "PriceMatrix")
                        .WithMany()
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceMatrix");
                });
#pragma warning restore 612, 618
        }
    }
}
